### ISSUE TITLE
undefined method `rels` for #<Neo4j::Core::Node:xxxxxx>

### ISSUE THREAD

**Issue by kroyagis** [neo4jrb/neo4j#1384]
After upgrading the `neo4j` gem version to 8.x, rake spec causes a following errors.
```
NoMethodError:
         undefined method `rels' for #<Neo4j::Core::Node:xxxxxxxxx>
```
```
 NoMethodError:
         undefined method `create_rel' for #<Neo4j::Core::Node:xxxxxxxxx>
```
Are certain methods deprecated from 8.x? I went through the docs but couldn't find anything. Please let me know.

Additional information which could be helpful if relevant to your issue:

### Runtime information:

Neo4j database version: 3.1.4
`neo4j` gem version: 8.0.17
`neo4j-core` gem version: 7.1.2

**Comment by cheerfulstoic** [comment]
I just responded [on StackOverflow](http://stackoverflow.com/questions/43854895/undefined-method-rels-for-neo4jcorenodexxxxxxxx/43870841#43870841)

The new `Node` and `Relationship` classes in the new API of `neo4j-core` were not designed with all of the methods that the old `Node` / `Relationship` classes because they were a mess to maintain and they duplicated a lot of the functionality of `ActiveNode` and `ActiveRel`.  It's suggested to use either `ActiveNode` / `ActiveRel` conventions for associations / query building or to write a Cypher query.

**Comment by kroyagis** [comment]
Thank you! This has gotten me one step closer to upgrading the app. I'm still very new to neo4j, but it's been a joyful learning experience so far!

**Comment by cheerfulstoic** [comment]
Excellent, glad you like it so far! ;) . I'm going to close this issue, but happy to answer other questions ([Gitter](https://gitter.im/neo4jrb/neo4j) is often a good place for questions)

**Comment by KapilMetacube** [comment]
Hi @cheerfulstoic , 
When i execute `Graph::Node::ChainNode.find(uuid).query_as(:c).....`, I'm getting
`NoMethodError - undefined method `query_as' for #<Neo4j::Core::Node:0x0000000f783278>:` error.
Is it related to the changes you elaborated above or anything different?

_Please help as I just upgraded to 8.x and was using this all over my project._
Also please just if there is a workaround (define or override the `methods`) so that I do not have to change the whole project.

Thanks

**Comment by thefliik** [comment]
@KapilMetacube,

I started using Neo4jrb in 8.x, so I'm not familiar with `Graph::Node::ChainNode.find(uuid).query_as(:c).....`. This being said, it looks like you're simply trying to start a query chain by finding a node with a particular`uuid`. Are you just using `neo4j-core`? Or are you using `neo4j`?

If you're just using neo4j-core, the new api is briefly introduced in the docs here: http://neo4jrb.readthedocs.io/en/9.0.x/UpgradeGuide.html#the-new-api

In general, you could construct your query with `Neo4j::Core::Query.new.match(n: {id: uuid}).where(..........).return(:n).limit(1).pluck(:n)`. Put another way, I think you could use find&replace  in your text editor / IDE to replace `Graph::Node::ChainNode.find(uuid).query_as(:c)` with `Neo4j::Core::Query.new.match(c: {id: your_uuid}).limit(1).......` and then proceed normally (though you should test this out on a code sample before updating your whole app with it).

This being said, you'd be constructing a highly unoptimized / slow query, because the query doesn't use any labels & will be a full database scan. The equivalent cypher query is ~ `MATCH (c {uuid: $the_id}) RETURN c LIMIT 1` (which, on most databases, isn't great).

If you know the labels associated with the node you're trying to find, you can greatly improve the query by making it something like `MATCH (c:AddYourLabel {uuid: $the_id}) RETURN c LIMIT 1`.

If you're using the `neo4j` gem, not just `neo4j-core`, you can construct the query by starting from an `ActiveNode` model. i.e. `Person.find(uuid).query_as(:c)..........` (which will automatically add in the appropriate labels)

**Comment by KapilMetacube** [comment]
@thefliik I'm not using neo4j-core for the purpose.
The rails app I'm working on uses the 4.x version of the neo4j gem. I just upgraded the neo4j gem version to the latest 9.x (making the changes required to connect to the server with new API and others to get the app running).
Example changes: 
Changed `Neo4j::Session.open(:server_db, neo4j_url)` to
```
adaptor = Neo4j::Core::CypherSession::Adaptors::HTTP.new(neo4j_url, wrap_level: :proc)
session = Neo4j::Core::CypherSession.new(adaptor)
# Is the below code thread safe?
Neo4j::ActiveBase.current_session = session
```

The query I'm talking about is on an `ActiveNode` model, like

```
class Graph::Node::ChainNode
  include Neo4j::ActiveNode  
  ....
end
```
In the older version i used to query, for example
_query_path is just a match query string_
```
node = Graph::Node::ChainNode.find_by_id(uuid)
node.query_as(:c).match(s: node.class.base_class.name).match(query_path).pluck('length(p)', 's.id') if node
```
which used to work fine and `node` returns the instance of `Graph::Node::ChainNode`.
But now when I run `node = Graph::Node::ChainNode.find_by_id(uuid)`, i'm getting `node` as an instance of `Neo4j::Core::Node`, which i do not expect and understand, Why?
And thus the error `NoMethodError - undefined method query_as for #Neo4j::Core::Node:0x0000000f783278:`

So I expected to be querying on an `ActiveNode` but was getting `Neo4j::Core::Node`.

Am I using neo4j-core `unintentionally`?
Is this have something to do with how I'm connecting to the server (creating session).

**Comment by thefliik** [comment]
@KapilMetacube, if `Graph::Node::ChainNode` is an `ActiveNode` model, then `node = Graph::Node::ChainNode.find_by_id(uuid)` should return an instance of `Graph::Node::ChainNode` NOT `Neo4j::Core::Node`. It sounds like you may be constructing your queries correctly and something else is going wrong.

`neo4jrb` expects for `ActiveNode` objects to have specific labels associated with them. Perhaps, because yours is a legacy app and the database was created using an older version of the gem, the nodes in the database don't have the labels which `neo4jrb` expects and this is throwing neo4j off.

If you jump into `rails console` and run
```
Graph::Node::ChainNode.mapped_label_names
```
You should see an array of strings which corresponds to the label names `neo4jrb` expects `Graph::Node::ChainNode` objects to have in the database. Can you confirm that your database nodes have the appropriate labels? If not, you may need to migrate your database to get things working.

Also, you have a typo in the sample query you shared: 
```
node.query_as(:c).match(s: node.class.base_class.name).match(query_path).pluck('length(p)', 's.id') if node
```
should be
```
node.query_as(:c).match(c: node.class.base_class.name).match(query_path).pluck('length(p)', 'c.id') if node
```
specifically, you're querying on `:c` but your match method is on `:s` and your pluck is on `:s`. 

Also, `neo4j` has a railstie that should automatically connect to your database (meaning you shouldn't need to do `adaptor = Neo4j::Core::CypherSession::Adaptors::HTTP.new(neo4j_url, wrap_level: :proc)`...etc...etc). I wouldn't expect manually connecting to the database to be a problem, however.

To make sure you are connected to the database, you could try running
```
Graph::Node::ChainNode.first.inspect
```
Inside `rails console`. That query should give an indication that it's returning something from the database.

**Comment by KapilMetacube** [comment]
@thefliik Thanks for your explanation above.
However, I was reviewing the docs and changed

```
adaptor = Neo4j::Core::CypherSession::Adaptors::HTTP.new(neo4j_url, wrap_level: :proc)
session = Neo4j::Core::CypherSession.new(adaptor)
# Is the below code thread safe?
Neo4j::ActiveBase.current_session = session
```
to
```
adaptor = Neo4j::Core::CypherSession::Adaptors::HTTP.new(neo4j_url, wrap_level: :proc)
Neo4j::ActiveBase.on_establish_session { Neo4j::Core::CypherSession.new(adaptor) }
```
and things just got working.

One more thing about your comment `neo4jrb has a railstie that should automatically connect to your database`, if I didn't create/establish a session I got `RuntimeError: No session defined!` error.

I will try to review why things started working after changing the session creation code(not totally sure). However, if you got some theory about it please share.

**Comment by KapilMetacube** [comment]
Hi @thefliik, @cheerfulstoic I'm now encountering a weird issue (at least for me).

```
class Graph::Node::ChainNode
  include Neo4j::ActiveNode  
  ....
end
```

```
irb(main):043:0>node = Graph::Node::ChainNode.last
irb(main):044:0> node.respond_to?(:query_as)
=> true
irb(main):045:0> node.query_as(:c)
> #<Query CYPHER: "MATCH (c) WHERE (ID(c) = {ID_c})">
```
So `query_as` method is working but `rel` method is raising error,
```
irb(main):046:0> node.respond_to?(:rel)
=> true
irb(main):047:0> node.rel
(irb):47:in `irb_binding': Neo4j::ActiveNode::Rels#rel at C:/Ruby24-x64/lib/ruby/2.4.0/forwardable.rb:157 forwarding to private method Neo4j::Core::Node#rel
NoMethodError: undefined method `rel' for #<Neo4j::Core::Node:0x000000158920f0>
        from C:/Ruby24-x64/lib/ruby/2.4.0/forwardable.rb:227:in `rel'
        from (irb):45
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/railties-5.0.6/lib/rails/commands/console.rb:65:in `start'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/railties-5.0.6/lib/rails/commands/console_helper.rb:9:in `start'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/railties-5.0.6/lib/rails/commands/commands_tasks.rb:78:in `console'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/railties-5.0.6/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/railties-5.0.6/lib/rails/commands.rb:18:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```

Am i missing something?

**Comment by cheerfulstoic** [comment]
Hey @KapilMetacube !

Sorry for the confusion (and thanks to @thefliik for the help).  So that you know, a lot of the changes that we're talking about happened from `neo4j` version 7.x to 8.x, so you might try upgrade to 7.x first for a simpler start.  I would also re-iterate the upgrade guide.  Since it was such a big change we tried to outline everything [there](http://neo4jrb.readthedocs.io/en/9.0.x/UpgradeGuide.html).  Since 8.x of the `neo4j` gem we're generally introducing smaller changes for each major version, so hopefully it won't be as disruptful in the future.

I believe that we got rid of the `rel` and `rels` methods in favor of defining your business logic in associations.  You should be able to make these yourself, though, like this:

```ruby
has_one :both, :rel, type: false, model_class: false
has_one :both, :rels, type: false, model_class: false
```

**Comment by KapilSachdev** [comment]
Hi @cheerfulstoic ,
I'm encountering an issue which might be related to this thread (cannot find any other issue with similarity).

When I try to get a relationship via `pluck('r')`, the object returned is an instance of `Neo4j::Core::Relationship` class, rather than the ActiveRel model (`Graph::Rel::ChainRel`) with that relationship.

```ruby
node = Graph::Node::ChainNode
rel = node.as(:c).query_as(:c).match('(c)<-[r:has_rel]-()').pluck('r') # relationships are instance of Neo4j::Core::Relationship
```

However, if I just require the file that defined that ActiveRel model (`require 'chain_rel.rb'`), the object now received with `pluck('r')` is an instance of `Graph::Rel::ChainRel`.


```ruby
require 'chain_rel.rb'

node = Graph::Node::ChainNode
rel = node.as(:c).query_as(:c).match('(c)<-[r:has_rel]-()').pluck('r') # relationships are now instance of Graph::Rel::ChainRel
```

Please help.
Thanks

**Comment by thefliik** [comment]
@KapilSachdev it sounds like `'chain_rel.rb'` hasn't been loaded at the time your query is running. In which case, `require 'chain_rel.rb'` is the correct solution.

Do you have reason to believe something else is going on?

`Neo4j::Core::Relationship` is a class provided by `neo4j-core` which the `neo4j` gem falls back on if you `pluck()` a relationship without an associated `ActiveRel` model.

**Comment by thefliik** [comment]
If you have reason to think that `'chain_rel.rb'` has already been loaded at the time your query has run, you could test this by referencing `Graph::Rel::ChainRel` in the code (which should raise an error if the class hasn't been loaded yet).

Something like:
```
Graph::Rel::ChainRel # <- will raise error if 'chain_rel.rb' hasn't been loaded

node = Graph::Node::ChainNode

rel = node.as(:c).query_as(:c).match('(c)<-[r:has_rel]-()').pluck('r') # relationships are instance of Neo4j::Core::Relationship
```

**Comment by KapilSachdev** [comment]
@thefliik , **Yes the file gets loaded** and `Graph::Rel::ChainRel` is available in the code and I can query on it.
Moreover, I had the issue before with other queries too, but I figured out another way to get the relationship (and not even have to require `chain_rel.rb`) and changed the queries. Below are the queries that I changed.
From:
```ruby
rel = to_node.as(:c).query_as(:c).match("(c)<-[r:`buy_from`]-(s:`Graph::Node::SupplyChainNode` {id: '#{from_node.id}'})").pluck('r').last # relationship is instance of Neo4j::Core::Relationship
```
To:
 ```ruby
rel = to_node.suppliers.match_to(from_node).rel # relationship is now instance of Graph::Rel::ChainRel
# This further clarifies that the file is being loaded because i dodn't require it this time
```
As you can see that above query was straight forward and change was easy, but i can't change the query now for which i'm encountring this issue in the above manner and had to `pluck(:r)`.
Does this clarify my issue further?
