### ISSUE TITLE
has_n not working: "Undefined method `has_n`" in model

### ISSUE THREAD

**Issue by markbao** [neo4jrb/neo4j#733]
Hi there, I upgraded from neo4j 3.0.0.alpha6 (yeah!) to 4.1.2 recently, and came across a problem where I was getting:

````
NoMethodError
undefined method `has_n' for #<Class:0x007fceab1eb7f8>
````

I'm using a simple system where I tag Posts to Tags, and I also want other models to have Tags, hence `has_n`.

### Details

Rails 4.2.1
neo4j (gem) 4.1.2
neo4j (community) 2.2.0
Ruby 2.2.1
OS X Yosemite 10.10.2

### Reproduce

I was able to reproduce this on latest neo4j with a new Rails project. Instructions below, or download the repo here: https://github.com/markbao/hasntest

#### Setup

````bash
# setup
rails new hasntest
cd hasntest
echo "gem 'neo4j'" >> Gemfile
bundle install

# neo4j
rake neo4j:install[community-2.2.0]
rake neo4j:start

# add models and controller (just so you can follow along)
touch app/models/post.rb
touch app/models/tag.rb
rails g controller posts
````

#### app/models/post.rb

```ruby
class Post
  include Neo4j::ActiveNode
  property :title
  has_n :tags
end
```

#### app/models/tag.rb

````ruby
class Tag
  include Neo4j::ActiveNode

  property :title
  has_n :tagged
end
````

#### app/controllers/posts_controller.rb

````ruby
class PostsController < ApplicationController
  def index
    Post.all
  end
end
````

#### config/routes.rb

Add:

````ruby
get 'posts' => 'posts#index'
````

#### Run

````bash
rails s
open http://localhost:3000/posts
````

#### Error

````
NoMethodError (undefined method `has_n' for Post(title: Object):Class):
  app/models/post.rb:4:in `<class:Post>'
  app/models/post.rb:1:in `<top (required)>'
  app/controllers/posts_controller.rb:3:in `index'
````

Any ideas here? `has_n` was working on 3.0.0.alpha6, and I see that it's included in `Neo4j::ActiveNode` (as far as I can tell), but it doesn't seem to be picking it up. Thanks!

**Comment by subvertallchris** [comment]
`has_n` was removed in 3.0's release. If I remember correctly, alpha 6 was the last to include it. See https://github.com/neo4jrb/neo4j/wiki/Neo4j-v3-Declared-Relationships for a thorough explanation of the new methods.

**Comment by markbao** [comment]
@subvertallchris Thank you for the fast response. Got it. What would you recommend to replace this polymorphic association?

Would it be a **Post** with:

````ruby
has_many :in, :tags, model_class: Tag
````

and a **Tag** with:

````ruby
has_many :out, :tagged, model_class: false
````

Or would you recommend something different? Thanks for your help.

**Comment by cheerfulstoic** [comment]
Yeah, that should work nicely for both the `tags` association and the `tagged` polymorphic association.  The other thing I would suggest is specifying a `type` like this:

    has_many :in, :tags, type: :tags

    has_many : out, :tagged, type: :tags, model_class: false


Alternatively you could do:

    has_many :in, :tags, origin: :tagged

    has_many : out, :tagged, type: :tags, model_class: false

We're actually planning on making the tag a required argument in our upcoming release because you generally want to specify it except in special circumstances.

**Comment by markbao** [comment]
Oh cool, I'll definitely make sure to include that. Thanks, Brian.

I'm a little confused as to how these relationships map to actual `create_rel` situations. Currently, I have a Taggable concern that handles tagging, and I'm currently doing this to 

````ruby
# `self` is the model, e.g. Post
# `tag` is the Tag
self.create_rel("TAG", tag)
tag.create_rel("TAGGED", self)
````

...is that correct, or am I missing something?

**Comment by cheerfulstoic** [comment]
`create_rel` is a lower-level method to be used on `Node` objects.  If you're using `ActiveNode` those models "wrap" the `Node` objects to provide a higher level abstraction.

To add a relationship via associations you can do either of the following:

```ruby
  self.tags << tag

  tag.tagged << self
```

If you do both you'll end up creating two relationships of the same type/direction.

**Comment by markbao** [comment]
Oh wow. So, I added the `type` as you suggested:

````ruby
has_many :in, :tags, type: :tags # post.rb
has_many :out, :tagged, type: :tags, model_class: false # tag.rb
````

And the relationship association to my Taggable concern:

````
self.tags << t
````

Now, what I was used to before was that a Post would have an outgoing TAG to a Tag, and an incoming TAGGED from a Tag, like so:

![graph copy](https://cloud.githubusercontent.com/assets/27594/6885163/04a8156e-d5e1-11e4-8806-1ef7daa90143.png)

But now (focusing in on one pair of nodes) with the `type` parameter, I'm only seeing *one* relationship of type `tags`:

![graph 1](https://cloud.githubusercontent.com/assets/27594/6885165/1876830a-d5e1-11e4-9fb2-739e56840b7e.png)

Is that how it's supposed to work? From working with the models a bit, it does seem to be working correctly. (I'm willing—nay, inclined—to accept that I've been doing it wrong all this time.)

**Comment by cheerfulstoic** [comment]
If you need both the `TAG` and `TAGGED` relationship types then you probably want t

```ruby
  has_many :in, :tags, type: :tag # post.rb
  has_many :in, :tagged, type: :tagged, model_class: false # tag.rb
```

Or something to that effect.  Depending on what is is that you need to do, you could even end up with four associations in your models:

 * One that represents the `TAG` relationship on `Post`
 * One that represents the `TAG` relationship on `Tag`
 * One that represents the `TAGGED` relationship on `Post`
 * One that represents the `TAGGED` relationship on `Tag`
 
because an association on a model represents one "side" of the relationship.

Again, you could simply have one relationship (and you'd need to choose either TAG or TAGGED) and then you could use that relationship to traverse from one node to the other in either direction.

**Comment by cheerfulstoic** [comment]
I'm around now on Gitter, so feel free to chime in there for a more real-time discussion

**Comment by markbao** [comment]
I decided to go with the single tag relationship, albeit uppercase to conform to tradition:

````ruby
has_many :in, :tags, type: :TAGS # post.rb
has_many :out, :tagged, type: :TAGS, model_class: false # tag.rb
````

Thanks for your help, @cheerfulstoic and @subvertallchris – I really appreciate it.

----

Here's my Taggable.rb concern for future searchers, which takes in a comma-separated `Model.tags_string` property and modifies the tag associations after saving:

````ruby
module Taggable
  extend ActiveSupport::Concern

  def tags_as_string
    if self.new?
      ''
    else
      tags.to_a.map(&:name).join(',')
    end
  end

  def compare_and_set_tags!
    # Get current tagset
    current_tagset = tags.to_a.map(&:name)

    # Get array for new tagset
    new_tagset = tag_string.split(',').map(&:strip)

    # Generate diff for new_tags
    new_tags = new_tagset - current_tagset

    # Generate diff for removed_tags
    removed_tags = current_tagset - new_tagset

    # Loop through each new tag to create a relationship
    new_tags.each do |new_tag|
      # Search for tag in existing tags
      t = Tag.find_by(name: new_tag)

      # Create tag if it doesn't exist
      if t.nil?
        t = Tag.create(name: new_tag)
      end

      # Associate tag with current model
      self.tags << t
    end

    # Loop through each removed tag to remove relationship
    removed_tags.each do |removed_tag|
      t = Tag.find_by(name: removed_tag)
      self.tags.delete(t) unless t.nil?
    end
  end
end
````

post.rb:

````ruby
include Taggable
...
property :tag_string
````

posts_controller.rb:
````ruby
  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @journal_article.update(journal_article_params)
        @journal_article.compare_and_set_tags!
...
````
