### ISSUE TITLE
Too many connections error

### ISSUE THREAD

**Issue by mattsnyder** [neo4jrb/neo4j#555]
I'm seeing this error when using the neo4j gem to talk to our Neo4j cluster. It literally just started. Do we need to tune our cluster settings? Have you seen this before? The CPU and memory load on the servers in nominal.

![screen shot 2014-11-06 at 12 57 01 pm](https://cloud.githubusercontent.com/assets/56926/4940880/a0bb1668-65de-11e4-9166-d062af9e10d6.png)

**Comment by cheerfulstoic** [comment]
This issue is almost a year old and three versions behind.  I'm going to close it, but please comment / reopen if you're still having trouble with 5.x or the 6.x alpha

**Comment by abuisman** [comment]
I am using version 6.1 of Neo4jrb and ruby 2.1.8 and I get the same error when, for example, trying to create a node ('GraphQuantity.create(....)'):

`Net::HTTP::Persistent::Error: too many connection resets (due to closed stream - IOError)`

**Comment by subvertallchris** [comment]
We've had reports of serious performance issues with Ruby 2.1. Can you
upgrade to 2.2.1 or greater?

**Comment by abuisman** [comment]
@subvertallchris Yes I figured that would be an issue. In theorie we could upgrade, but seeing as we'd integrate neo4j in a pretty big existing project it would take some more work to do so. I was hoping this issue would've been fixed for 2.1.x. No such luck I guess? ;)

**Comment by subvertallchris** [comment]
Unfortunately not. All signs indicated it being an issue in a dependency,
my money is with Net::Http::Persistent or Faraday, so it's out of our
hands.

**Comment by abuisman** [comment]
That is unlucky for me :(. 
I just checked with ruby 2.2.2 and it doesn't work either. I will try 2.3.x, or would that futile?

**Comment by subvertallchris** [comment]
Interesting. What's the query that you're trying to execute? Also, can you tell me a bit about your environment? Is the server local and what OS are you running?

**Comment by subvertallchris** [comment]
And no, if 2.2.2 isn't behaving then I don't expect 2.3.x will.

**Comment by abuisman** [comment]
Haha yes you are probably right.

I am running `2.3.2 - COMMUNITY` version on OS X using the community edition .app
My Rails version is '4.2.3'.

The query:

`GraphQuantity.all`

My model:

````
class GraphQuantity
  include Neo4j::ActiveNode

  property :name, type: String

  has_many :in, :children, type: :child_quantity_of, model_class: :GraphQuantity
  has_one :out, :parent, origin: :children
end
````

**Comment by subvertallchris** [comment]
Seems straightforward enough. How many nodes are you expecting to have returned from the db?

**Comment by abuisman** [comment]
Right now there are 0 in the database. I created a new one just to play around with.

**Comment by subvertallchris** [comment]
Ah, I see. In your code or even in the Rails console, one time, try calling `GraphQuantity.first` before doing anything else. That might make some schema changes that are known to cause problems when run within transactions.

**Comment by abuisman** [comment]
Sadly that doesn't work either:

````
[3] pry(main)> GraphQuantity.first
Net::HTTP::Persistent::Error: too many connection resets (due to closed stream - IOError) after 0 requests on 2237191000, last used 1.440335 seconds ago
from /Users/achilleas/.rbenv/versions/2.3.0/lib/ruby/2.3.0/net/protocol.rb:211:in `write'
[4] pry(main)> GraphQuantity.all
Net::HTTP::Persistent::Error: too many connection resets (due to closed stream - IOError) after 0 requests on 2237191000, last used 4.27705 seconds ago
from /Users/achilleas/.rbenv/versions/2.3.0/lib/ruby/2.3.0/net/protocol.rb:211:in `write'
````

**Comment by subvertallchris** [comment]
That is really weird... Is the Neo4j web console working?

**Comment by abuisman** [comment]
Yes both the web console and the neo4j-shell are working fine. I just created a node and it works.

**Comment by subvertallchris** [comment]
Do you have auth enabled on the Neo4j server? Has it ever worked in the
past with the Neo4j gem or is this your first time?

You can also try going through `bundle exec irb`:

```
require 'neo4j-core'
Neo4j::Session.open(:server_db, 'http://localhost:7474')
Neo4j::Session.current.query.match(:n).limit(1).pluck(:n).first
```

If that works, we might be able to troubleshoot something more specific.

**Comment by abuisman** [comment]
I have an other (older) project that I generated with Neo4j from the get go that works fine with neo4j 5.2.7, so it is either an issue with the version or a conflict with another gem.

I have auth enabled so I ran:

````
Neo4j::Session.open(:server_db, 'http://localhost:7474', basic_auth: { username: 'neo4j', password: '....'})
=> Neo4j::Server::CypherSession url: 'http://localhost:7474/db/data/' version: '2.3.2'

[4] pry(main)> Neo4j::Session.current.query.match(:n).limit(1).pluck(:n).first
NoMethodError: undefined method `fetch' for nil:NilClass
````

**Comment by abuisman** [comment]
The conflicting gem seems unlikely come to think of it because I ran the above in a 'clean' pry.

**Comment by subvertallchris** [comment]
I think there is a bug somewhere in the sample query I gave you or the code
when parsing its response... We just need to see if we're able to
successfully perform a basic Cypher query through neo4j-core. If we can,
then we assume that your session is ok and there's a problem with another
operation in the more Rails-oriented gem.

A little background for you: Neo4j-core is a dependency of Neo4j, it
handles all communication with the server among other things.
The modification of indexes and constraints as defined in the models begins
after a session is established and a model is loaded, and this process can
sometimes cause problems. This isn't one of the problems it normally causes
but it might be possible if there is a corrupt index or significant number
of nodes, requiring a brutal lock to scan and verify uniqueness.

Can you also make sure you are using the most recent patch release of the
Neo4j gem if you haven't already?

**Comment by abuisman** [comment]
I have this version in my Gemfile: `gem 'neo4j', '~> 6.1', '>= 6.1.3'`
I added it today, so it should be the newest.

**Comment by abuisman** [comment]
I just ran the query you told me earlier and now it looks like it worked:

````
[2] pry(main)> Neo4j::Session.open(:server_db, 'http://localhost:7474', basic_auth: { username: 'neo4j', password: 'fietsen999'})
=> Neo4j::Server::CypherSession url: 'http://localhost:7474/db/data/' version: '2.3.2'
[4] pry(main)> Neo4j::Session.current.query.match(:n).limit(1).pluck(:n).first
=> CypherNode 0 (70146770242820)
````

**Comment by abuisman** [comment]
When I run the above in my rails console I get an error again:

````
[4] pry(main)> Neo4j::Session.current.query.match(:n).limit(1).pluck(:n).first
 CYPHER 6ms MATCH n RETURN n LIMIT {limit_1} | {:limit_1=>1}
Net::HTTP::Persistent::Error: too many connection resets (due to closed stream - IOError) after 0 requests on 2281254360, last used 1453405996.86403 seconds ago
from /Users/achilleas/.rbenv/versions/2.3.0/lib/ruby/2.3.0/net/protocol.rb:211:in `write'
````

So it seems like a conflicting gem or configuration. What do you think?

**Comment by abuisman** [comment]
Ok so I disabled a whole lot of gems and now it works. Time to trial-and-error the gems one by one ;) I will keep you updated. Thanks a lot so far for your time and patience :+1:

**Comment by abuisman** [comment]
It seems I have found the culprit:

`gem 'newrelic_rpm', '~> 3.13.2.302'`

When I comment this out and rebundle neo4jrb works again :). 

I will try updating it and I will try the other ruby versions as well to check it they work without/the updated newrelic.

**Comment by abuisman** [comment]
`gem 'newrelic_rpm', '~> 3.14', '>= 3.14.1.311'`

Works with Neo4jrb :) Now for Ruby 2.1.x ;).

**Comment by abuisman** [comment]
"The original ruby version I tried using (`2.1.2`) works once I update the newrelic_rpm version as above :). Thanks a lot Chris @subvertallchris, for the patience and brainstorming."

Was what I had written until I noticed that running `GraphQuantity.first` didn't work again, but when I ran `bin/spring stop && bin/rails c` again it worked again... When I was debugging gems I suddenly noticed the same 'flickering' when I was checking if it really was newrelic or not. It seems as if sometimes the connection works and sometimes it doesn't, but stopping spring and then opening the rails console often helps! I will investigate this some more tomorrow with the same older version of newrelic to see if it really is that, or if there is a flickering caused by something else.

**Comment by subvertallchris** [comment]
That's really interesting, please keep us posted!

**Comment by cheerfulstoic** [comment]
Awesome debugging, thanks!  Hopefully this will help somebody else who comes along!

**Comment by abuisman** [comment]
Good morning guys :). Welcome @cheerfulstoic thanks for joining in ;)

Apparently newrelic wasn't really it, I created a screencapture showing what is going on now:
https://achilleas.nl/neo4j-why.mp4

Apparently the connection is very unreliable. I will try with Ruby 2.3, but first I will check if running neo4j in a Docker container is more stable than using the `.app` version.

**Comment by abuisman** [comment]
Ok so I believe I really solved it this time ;).

The flickering threw me off and made me think it was newrelic. Now I disabled the gem `gem 'fakeweb', '~> 1.3.0'` and it turns out this was _really_ the issue. I will start playing around with neo4jrb today and will discover if this really solved the issue, but I am pretty confident. Pretty logical if you think of it :).

If it turns out Fakeweb is the issue here I will open an issue over there to see if they can fix it.

**Comment by cheerfulstoic** [comment]
That's why I always use real webz

![http://www.smh.com.au/content/dam/images/1/u/j/b/6/image.related.articleLeadwide.620x349.1ujov.png/1331095890303.jpg](http://www.smh.com.au/content/dam/images/1/u/j/b/6/image.related.articleLeadwide.620x349.1ujov.png/1331095890303.jpg)

**Comment by abuisman** [comment]
@cheerfulstoic The real question is why fakeweb was in de :development group in the Gemfile. There is no real issue with using fakeweb in tests.

**Comment by abuisman** [comment]
So I have been working with Neo4jrb all day and I haven't had any problems with the connection since I removed 'fakeweb' from the Gemfile. My issue is solved, even in Ruby 2.1. Thanks @subvertallchris  @cheerfulstoic :)

I will point the guys from Fakeweb over to here.

**Comment by subvertallchris** [comment]
Not sure I'd hold my breath on a response. That gem hasn't been updated for a few years. :-(

**Comment by abuisman** [comment]
Maybe my issue will spark some sudden inspiration to work on it again ;) :)
